services:
  db:
    container_name: postgres-fullstack
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
  backend:
    container_name: backend-fullstack
    volumes:
      - pgdata:/pgdata
    build:
      context: ./
      dockerfile: Dockerfile.backend
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - '${PORT}:3002'
    environment:
      - PORT=${PORT}
      - HOST=${HOST}
      - DB_HOST=db
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx-fullstack
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/ssl:/etc/nginx/ssl:ro
      - nginx_cache:/var/cache/nginx
    user: 'nginxuser'
    restart: always
volumes:
  postgres-data:
  pgdata:
  nginx_cache:
