name: Deploy Backend to EC2

on:
  push:
    branches:
      - BE-20-add-github-actions

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          ref: BE-20-add-github-actions

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.AWS_PORT }}
          script: |
            set -x 
            cd app
            git pull git@github.com:katelovestocode/backend-internship.git --branch BE-20-add-github-actions --single-branch
            cd backend-internship

            if [ ! -d .git ]; then
            echo "Error: Failed to clone the repository."
            exit 1
            fi

            echo "PORT=${{ secrets.PORT }}" > .env
            echo "HOST=${{ secrets.HOST }}" >> .env
            echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
            echo "DB_CONNECTION=${{ secrets.DB_CONNECTION }}" >> .env
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            echo "ACCESS_SECRET_KEY=${{ secrets.ACCESS_SECRET_KEY }}" >> .env
            echo "REFRESH_SECRET_KEY=${{ secrets.REFRESH_SECRET_KEY }}" >> .env
            echo "ACTION_SECRET_KEY=${{ secrets.ACTION_SECRET_KEY }}" >> .env
            echo "AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}" >> .env
            echo "AUTH0_ISSUER_URL=${{ secrets.AUTH0_ISSUER_URL }}" >> .env
            echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env
            echo "AUTH0_JWKS_URL=${{ secrets.AUTH0_JWKS_URL }}" >> .env
          # Stop backend service only
          #docker-compose stop backend
          # Remove backend service only
          # docker-compose rm -f backend

          # if [ $? -ne 0 ]; then
          # echo "Error: Failed to build the Docker image."
          # exit 1
          # fi

          # Update and restart, build with new backend service
          # docker-compose up --build -d

          # if [ $? -ne 0 ]; then
          # echo "Error: Failed to start the Docker container."
          # exit 1
          # fi
